import React from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,ArrowUpRight,Truck,ShieldCheck,RotateCcw,Sparkles} from 'lucide-react';
import {products,categories,customerReviews} from '../data/products';
import ProductCard from '../components/ProductCard';

const HomePage:React.FC=()=> <div className="page-fade bg-[#f4f1eb] text-[#171614]">
<section className="relative overflow-hidden bg-[#171614] text-[#f7f4ed] min-h-[86vh] flex items-end">
<div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_25%,#6b5a4622,transparent_30%),radial-gradient(circle_at_20%_70%,#c9a66b18,transparent_28%)]"/>
<div className="absolute right-[8%] top-[12%] w-40 h-40 sm:w-64 sm:h-64 rounded-full border border-[#c9a66b33] float-soft"/>
<div className="relative max-w-7xl mx-auto w-full px-5 sm:px-8 lg:px-10 py-20 sm:py-28">
<div className="max-w-4xl reveal"><p className="text-[#c9a66b] text-[11px] font-semibold tracking-[.3em] uppercase mb-7">KAIXY / NEW SEASON 2026</p><h1 className="font-syne text-[clamp(4rem,10vw,9rem)] leading-[.82] tracking-[-.065em] font-bold">Everyday<br/><em className="font-normal text-[#c9a66b]">made better.</em></h1><p className="max-w-lg text-[#bdb8ae] text-sm sm:text-base leading-7 mt-9">A considered collection of fashion, technology and objects for modern everyday life.</p><div className="flex flex-wrap gap-3 mt-9"><Link to="/shop" className="!bg-[#f7f4ed] !text-[#171614] btn-primary">Shop the edit <ArrowRight size={16}/></Link><Link to="/info/about" className="!bg-transparent !text-[#f7f4ed] !border-[#ffffff33] btn-secondary">Our story</Link></div></div>
</div></section>
<section className="bg-[#c9a66b] text-[#171614] py-4 overflow-hidden"><div className="flex whitespace-nowrap gap-12 text-[10px] font-bold tracking-[.25em] uppercase" style={{width:'max-content',animation:'marquee 22s linear infinite'}}>{Array.from({length:8},(_,i)=><span key={i}>KAIXY — CURATED GOODS — FREE SHIPPING — EASY RETURNS</span>)}</div></section>
<section className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-10 py-20 sm:py-28"><div className="flex items-end justify-between mb-10"><div><p className="section-label !text-[#8b6a35]">The edit</p><h2 className="font-syne text-4xl sm:text-6xl tracking-[-.04em]">Shop by category</h2></div><Link to="/shop" className="hidden sm:flex items-center gap-2 text-xs uppercase tracking-widest">All products <ArrowUpRight size={14}/></Link></div>
<div className="grid lg:grid-cols-5 border-t border-[#17161433]">{categories.map((c,i)=><Link key={c.id} to={`/shop?category=${c.name}`} className="group relative min-h-[270px] lg:min-h-[390px] border-b lg:border-b-0 lg:border-r border-[#17161433] last:border-r-0 overflow-hidden p-6 sm:p-8 flex flex-col justify-between bg-[#f4f1eb] hover:text-white transition-colors duration-500"><img src={c.image} alt="" className="absolute inset-0 w-full h-full object-cover opacity-0 group-hover:opacity-55 scale-110 group-hover:scale-100 transition-all duration-700"/><div className="absolute inset-0 bg-[#171614] opacity-0 group-hover:opacity-70 transition-opacity"/><div className="relative flex justify-between text-xs"><span>0{i+1}</span><ArrowUpRight className="group-hover:rotate-45 transition-transform duration-300" size={17}/></div><div className="relative"><h3 className="font-syne text-2xl sm:text-3xl font-bold leading-none">{c.name}</h3><p className="text-xs opacity-60 mt-3 max-w-[180px]">{c.description}</p></div></Link>)}</div></section>
<section className="bg-[#e7e1d7] py-20 sm:py-28"><div className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-10"><div className="flex items-end justify-between mb-10"><div><p className="section-label !text-[#8b6a35]">Curated now</p><h2 className="font-syne text-4xl sm:text-6xl tracking-[-.04em]">Trending</h2></div><Link to="/shop" className="flex items-center gap-2 text-xs uppercase tracking-widest">Discover <ArrowRight size={14}/></Link></div><div className="grid grid-cols-2 md:grid-cols-4 gap-x-4 sm:gap-x-6 gap-y-10">{products.filter(p=>p.isTrending).slice(0,4).map((p,i)=><div key={p.id} className="reveal" style={{animationDelay:`${i*.08}s`}}><ProductCard product={p}/></div>)}</div></div></section>
<section className="bg-[#171614] text-white py-16"><div className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-10 grid md:grid-cols-3 divide-y md:divide-y-0 md:divide-x divide-white/15">{[[Truck,'Free delivery','On orders over $100'],[ShieldCheck,'Considered quality','Products worth keeping'],[RotateCcw,'Easy returns','A simple 30-day window']].map(([I,t,s])=><div key={String(t)} className="py-8 md:px-10 first:pt-0 md:first:pl-0 md:py-3 last:pb-0 flex items-center gap-5"><I size={22} className="text-[#c9a66b] shrink-0"/><div><h3 className="font-syne font-bold">{String(t)}</h3><p className="text-xs text-white/50 mt-1">{String(s)}</p></div></div>)}</div></section>
<section className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-10 py-20 sm:py-28"><div className="max-w-2xl"><p className="section-label !text-[#8b6a35]">From our customers</p><h2 className="font-syne text-4xl sm:text-6xl tracking-[-.04em]">Good things,<br/>said simply.</h2></div><div className="grid md:grid-cols-2 gap-5 mt-12">{customerReviews.slice(0,2).map(r=><article key={r.id} className="border-t-2 border-[#171614] pt-6"><p className="text-[#8b6a35] tracking-widest text-sm">★★★★★</p><h3 className="font-syne text-xl font-bold mt-5">{r.title}</h3><p className="text-sm text-[#68645d] leading-7 mt-3">{r.body}</p><p className="text-[11px] uppercase tracking-widest mt-6">{r.author}</p></article>)}</div></section>
</div>;
export default HomePage;
