import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';

const Footer: React.FC = () => (
  <footer className="bg-zinc-950 text-zinc-400 mt-24">
    <div className="border-b border-zinc-800"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div className="flex flex-col md:flex-row md:items-center justify-between gap-6"><div><h3 className="font-syne text-xl font-bold text-white mb-1">Stay in the loop.</h3><p className="text-sm text-zinc-500">New arrivals, exclusive drops, and early access to sales.</p></div><div className="flex gap-0 w-full md:w-auto md:max-w-sm"><input type="email" placeholder="Your email address" className="flex-1 bg-zinc-900 border border-zinc-800 text-sm text-zinc-300 placeholder-zinc-600 px-4 py-3 focus:outline-none focus:border-amber-600 transition-colors duration-200 min-w-0"/><button className="bg-amber-600 hover:bg-amber-700 text-white px-4 py-3 transition-colors duration-200"><ArrowRight size={16}/></button></div></div></div></div>
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div className="grid grid-cols-2 md:grid-cols-4 gap-8 lg:gap-12"><div className="col-span-2 md:col-span-1"><Link to="/" className="font-syne font-bold text-2xl text-white tracking-tight hover:text-amber-500 transition-colors duration-200 block mb-4">KAIXY</Link><p className="text-sm text-zinc-500 leading-relaxed max-w-xs">A curated marketplace for those who refuse to compromise on quality, design, or experience.</p><div className="flex items-center gap-3 mt-6">{['IG','TW','YT'].map(s=><a key={s} href="#" className="w-9 h-9 rounded-full bg-zinc-900 flex items-center justify-center hover:bg-amber-600 transition-colors duration-200"><span className="text-zinc-400 text-[10px] font-bold">{s}</span></a>)}</div></div>
      <div><h4 className="text-white text-xs font-semibold tracking-widest uppercase mb-5">Shop</h4><ul className="space-y-3">{['Fashion','Footwear','Electronics','Accessories','Home'].map(cat=><li key={cat}><Link to={`/shop?category=${cat}`} className="text-sm text-zinc-500 hover:text-white transition-colors duration-200">{cat}</Link></li>)}</ul></div>
      <div><h4 className="text-white text-xs font-semibold tracking-widest uppercase mb-5">Company</h4><ul className="space-y-3">{['About Us','Careers','Press','Sustainability','Contact'].map(item=><li key={item}><a href="#" className="text-sm text-zinc-500 hover:text-white transition-colors duration-200">{item}</a></li>)}</ul></div>
      <div><h4 className="text-white text-xs font-semibold tracking-widest uppercase mb-5">Support</h4><ul className="space-y-3">{['Track Order','Returns & Refunds','Shipping Info','Size Guide','FAQ'].map(item=><li key={item}><a href="#" className="text-sm text-zinc-500 hover:text-white transition-colors duration-200">{item}</a></li>)}</ul></div>
    </div></div>
    <div className="border-t border-zinc-900"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-5 flex flex-col sm:flex-row items-center justify-between gap-3"><p className="text-xs text-zinc-600">© 2025 KAIXY. All rights reserved.</p><div className="flex items-center gap-5">{['Privacy Policy','Terms of Service','Cookies'].map(x=><a key={x} href="#" className="text-xs text-zinc-600 hover:text-zinc-400 transition-colors duration-200">{x}</a>)}</div></div></div>
  </footer>
);
export default Footer;
