import React, { useState, useEffect, useRef } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { Search, Heart, ShoppingBag, X, Menu } from 'lucide-react';
import { useStore } from '../store/useStore';
import { products } from '../data/products';

const Navbar: React.FC = () => {
  const [scrolled,setScrolled]=useState(false),[searchOpen,setSearchOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[searchQuery,setSearchQuery]=useState('');
  const [searchResults,setSearchResults]=useState<typeof products>([]); const searchRef=useRef<HTMLDivElement>(null); const navigate=useNavigate(); const location=useLocation(); const {cartCount,wishlist}=useStore();
  useEffect(()=>{const h=()=>setScrolled(window.scrollY>20);window.addEventListener('scroll',h);return()=>window.removeEventListener('scroll',h)},[]);
  useEffect(()=>{const h=(e:MouseEvent)=>{if(searchRef.current&&!searchRef.current.contains(e.target as Node)){setSearchOpen(false);setSearchQuery('')}};document.addEventListener('mousedown',h);return()=>document.removeEventListener('mousedown',h)},[]);
  useEffect(()=>{if(searchQuery.trim().length>1){const q=searchQuery.toLowerCase();setSearchResults(products.filter(p=>p.name.toLowerCase().includes(q)||p.brand.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)||p.tags?.some(t=>t.includes(q))).slice(0,5))}else setSearchResults([])},[searchQuery]);
  useEffect(()=>{setMenuOpen(false)},[location.pathname]);
  const navLinks=[{label:'Home',path:'/'},{label:'Shop',path:'/shop'}]; const isActive=(p:string)=>p==='/'?location.pathname==='/':location.pathname.startsWith(p);
  return <><nav className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${scrolled?'bg-white/95 backdrop-blur-md border-b border-zinc-100 shadow-sm':'bg-white border-b border-zinc-100'}`}><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between h-16"><Link to="/" className="font-syne font-bold text-xl tracking-tight text-zinc-900 hover:text-amber-600 transition-colors duration-200">KAIXY</Link><div className="hidden md:flex items-center gap-8">{navLinks.map(l=><Link key={l.path} to={l.path} className={`nav-link ${isActive(l.path)?'text-zinc-900 font-semibold':''}`}>{l.label}</Link>)}</div><div className="flex items-center gap-1"><button onClick={()=>setSearchOpen(!searchOpen)} className="w-10 h-10 flex items-center justify-center text-zinc-600 hover:text-zinc-900"><Search size={18}/></button><Link to="/wishlist" className="relative w-10 h-10 flex items-center justify-center text-zinc-600 hover:text-zinc-900"><Heart size={18}/>{wishlist.length>0&&<span className="absolute top-1.5 right-1.5 w-4 h-4 bg-amber-600 text-white text-[9px] font-bold flex items-center justify-center rounded-full">{wishlist.length}</span>}</Link><Link to="/cart" className="relative w-10 h-10 flex items-center justify-center text-zinc-600 hover:text-zinc-900"><ShoppingBag size={18}/>{cartCount()>0&&<span className="absolute top-1.5 right-1.5 w-4 h-4 bg-zinc-900 text-white text-[9px] font-bold flex items-center justify-center rounded-full">{cartCount()}</span>}</Link><button onClick={()=>setMenuOpen(!menuOpen)} className="md:hidden w-10 h-10 flex items-center justify-center text-zinc-600 ml-1">{menuOpen?<X size={18}/>:<Menu size={18}/>}</button></div></div></div>
  {searchOpen&&<div ref={searchRef} className="border-t border-zinc-100 bg-white px-4 sm:px-6 lg:px-8 py-3 scale-in"><div className="max-w-7xl mx-auto relative"><div className="flex items-center gap-3"><Search size={16} className="text-zinc-400"/><input autoFocus placeholder="Search products, brands, categories..." value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&searchQuery.trim()){navigate(`/shop?search=${encodeURIComponent(searchQuery)}`);setSearchOpen(false);setSearchQuery('')}}} className="flex-1 text-sm text-zinc-900 placeholder-zinc-400 focus:outline-none py-1"/>{searchQuery&&<button onClick={()=>setSearchQuery('')} className="text-zinc-400"><X size={14}/></button>}</div>{searchResults.length>0&&<div className="absolute top-full left-0 right-0 bg-white border border-zinc-100 shadow-lg mt-2 z-50 scale-in">{searchResults.map(product=><button key={product.id} onClick={()=>{navigate(`/product/${product.id}`);setSearchOpen(false);setSearchQuery('')}} className="w-full flex items-center gap-3 px-4 py-3 hover:bg-zinc-50 text-left"><img src={product.image} alt={product.name} className="w-10 h-12 object-cover bg-zinc-100"/><div className="flex-1 min-w-0"><p className="text-sm font-medium text-zinc-900 truncate">{product.name}</p><p className="text-xs text-zinc-500">{product.category}</p></div><span className="text-sm font-semibold text-zinc-900">${product.discount?(product.price*(1-product.discount/100)).toFixed(0):product.price}</span></button>)}<button onClick={()=>{navigate(`/shop?search=${encodeURIComponent(searchQuery)}`);setSearchOpen(false);setSearchQuery('')}} className="w-full px-4 py-3 text-xs font-medium text-amber-600 hover:bg-amber-50 text-center border-t border-zinc-100">See all results for "{searchQuery}"</button></div>}</div></div>}
  {menuOpen&&<div className="md:hidden border-t border-zinc-100 bg-white px-6 py-4 scale-in"><div className="flex flex-col gap-4">{navLinks.map(l=><Link key={l.path} to={l.path} className={`text-sm font-medium ${isActive(l.path)?'text-zinc-900':'text-zinc-500'}`}>{l.label}</Link>)}</div></div>}</nav><div className="h-16"/></>;
}; export default Navbar;
